### ISSUE TITLE
expose System to sendSystemMessage from components outside the Plugin system

### ISSUE THREAD

**Issue by xosofox** [bitExpert/mntyjs#10]
Is it possible to fire system events "from the outside"?

For example, do something like

> mnty.system.sendSystemMessage("reload", data)

and thus trigger an event from within another piece of code?

**Comment by dropdevcoding** [comment]
Well, mntyjs isn't designed to be used as in the example you provided. 
Mntyjs is all about Plugins, which provide functionality to DOM elements (kind of "controllers"), managed by a PluginManager and loosely coupled using the PluginManager's event bus.

Could you please provide / describe a more detailed use case so I may understand better what you are trying to achieve?

**Comment by xosofox** [comment]
The event bus seems not to be accessible from the outside. So in case I want to trigger events from other, not mntyjs based components, I'm looking for an option there.

On the other hand side, as mntyjs plugins on startup seem to take all data from data-attributes, it looks like there is no way to inject another, already existing event bus instance (like `Backbone.Wreqr.EventAggregator`) into a plugin.

So, looks like all plugins are interconnected but isolated from the outside world (which is good on one hand) but there seems to be no way to interact (besides the `window` scope maybe...)

**Comment by dropdevcoding** [comment]
> it looks like there is no way to inject another, already existing event bus instance (like Backbone.Wreqr.EventAggregator) into a plugin.

You may inject everything you want by providing it using a require.js module (dont' forget to configure it using require.config)

``` javascript
define(['MyAwesomeEventBus', 'Plugin'], function (eventBus, Plugin) {
    return Plugin.extend({
        execute: function (dfd) {
            eventBus.doStuff();
        }
    });
});
```

everything you need to do is to provide your EventBus instance using a requirejs module.

I never tried to combine mntyjs with Backbone because they implement different approaches.

Another way getting access to the PluginManager depends on the version you are using.
If you use a version prior 1.2.0, the PluginManager is a singleton instance and you may access it using:

``` javascript
require(['PluginManager'], function (PluginManager) {
    PluginManager.on('myevent', function (payload) {
       console.log('payload', payload);
    });

    PluginManager.fire('myevent', {
       my: 'payload'
    });
});
```

If you are using 1.2.0 the PluginManager is not singleton anmyore and will be instanciated in src/AutoLoader.js

You could set autoMount and autoUnmount option to false, copy the autloader and place it into a customized script, where you instanciate the PluginManager manually. You may store it into a global variable but this may cause side effects since requirejs works async so please be careful.

**Comment by xosofox** [comment]
Thanks, injecting my EventAggregator instance via require.js into the plugin is a working solution.

**Comment by dropdevcoding** [comment]
You're welcome.
